sudo: required
env:
- GHCVER=7.8.4
- GHCVER=7.10.3
- GHCVER=8.0.2
- GHCVER=8.2.2
- GHCVER=8.4.1
- GHCVER=head

script:
- curl -sL https://raw.github.com/ndmitchell/neil/master/travis.sh | sh

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - .stack-work